
data_ingestion:
  raw_path: "data/raw"
  test_path: "data/test"
  train_path: "data/train"
 

data_transform:
  preprocessor_path: "artifacts/models"

model_trainer:
  model_path: "artifacts/models"

container_name: "sample-data"
blob_name: "german_credit_data/german_credit_data.csv"